// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vizallas.Data;

#nullable disable

namespace Vizallas.Migrations
{
    [DbContext(typeof(VizallasDbContext))]
    partial class VizallasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Vizallas.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("folyo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("varos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("vizallas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
